### PR TITLE
Update for lodash 4.x and optimize for web bundlers

### PR DESCRIPTION
**Pull request by jonjaques**
Hi there,

This does what it says on the tin. Let me know if there's anything you like changed.

### CODE REVIEW

**Comment by jonjaques** [comment]
Hey! I just ran the examples.js script. 
Only 'major' change was the switch from `_.merge` => `_.mergeWith`. 

Is there anything else you'd like me to do? I understand this would likely require a major version bump.

**Comment by bigShai** [comment]
Why the change?
What's the advantage mergeWith gives?

**Comment by jonjaques** [comment]
https://lodash.com/docs#merge

`merge` no longer takes the `customizer` function, that has been moved to `mergeWith`.

**Comment by bigShai** [comment]
Got it, Thanks.
I'll do some tests to make sure everything works normally.

**Comment by s0j0hn** [comment]
please, merge for security reasons.

**Pull request closed without merging**
